apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: backendd/mizotakhteh.book:1-cicd
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: book
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "0.1"
              memory: "100Mi"
            requests:
              cpu: "0"
              memory: "0"