apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postgres
            - secretRef:
                name: mizotakhteh
          ports:
            - name: tcp
              containerPort: 5432
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 0m
              memory: 0Mi
