apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
      targetPort: tcp
  selector:
    app: postgres