name: Main
on:
  push:
    branches:
      - master

jobs:
  prod-deploy:
    strategy:
      matrix:
        app:
          - book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONF }}
        with:
          args: --context outi apply -k ${{ matrix.app }}/overlays/dev